In [0]:
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings('ignore')

## functions

In [0]:
# standartization function (excl_col - columns to exclude, verd - to plot or not)
def my_stnd(x, excl_cols=[],):
    x_std = x.copy().astype(float)
    for i in ([i for i in range(x_std.shape[0]) if i not in excl_cols]):
        x_std[i] = (x[i] - x[i].mean()) / x[i].std()

    return x_std

# sigmoid function
def sigmoid(z):
    res = 1 / (1 + np.exp(-z))
    return res

# log less error
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred) + (1.0 - y) * np.log(1.0 - y_pred))
    err = np.sum(err)
    return err

# evaluate log regression model
def eval_model_log(x, y, iterations, alpha=1e-4, verb=True):
    np.random.seed(42)
    w = np.random.randn(x.shape[0])
    for i in range(1, iterations+1):
        z = np.dot(w, x)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/x.shape[1] * np.dot((y_pred - y), x.T))
        if verb == True:
            if i % (iterations / 10) == 0:
                print(i, w, err)
    return w

## data upload

In [0]:
x = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 1, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]])

y = np.array([0, 0, 1, 0, 1, 0, 1, 0, 1, 1], dtype = np.float64)

## build, fit & predict

In [15]:
eval_model_log(my_stnd(x, [0, 1, 3]), y, iterations=1000, alpha=1e-4)

100 [ 0.49282748 -0.15007528  0.64748973  1.51727915] 1.2014814214705334
200 [ 0.48896219 -0.16184918  0.64728128  1.51155738] 1.1828456288538924
300 [ 0.48511874 -0.17358386  0.64706349  1.50586552] 1.1643525542846556
400 [ 0.4812976  -0.18527698  0.64683669  1.50020462] 1.1460086359433084
500 [ 0.47749927 -0.19692597  0.64660127  1.4945758 ] 1.127820879406358
600 [ 0.47372426 -0.20852799  0.6463577   1.48898028] 1.109796908143704
700 [ 0.46997312 -0.22007992  0.6461065   1.48341934] 1.0919450148769096
800 [ 0.46624642 -0.23157833  0.64584825  1.47789438] 1.074274212586137
900 [ 0.46254476 -0.24301946  0.64558365  1.4724069 ] 1.0567942835649755
1000 [ 0.45886878 -0.25439917  0.64531344  1.46695851] 1.0395158244739489


array([ 0.45886878, -0.25439917,  0.64531344,  1.46695851])

In [16]:
eval_model_log(my_stnd(x, [0]), y, iterations=1000, alpha=1e-4)

100 [ 0.49635335 -0.14077362  0.64537112  1.52180639] 0.7625324736043118
200 [ 0.49598986 -0.14327981  0.64305753  1.52058688] 0.7612071473029914
300 [ 0.49562367 -0.14578284  0.64074779  1.51937134] 0.7598859435316546
400 [ 0.49525481 -0.14828271  0.63844189  1.51815977] 0.7585688613630801
500 [ 0.49488327 -0.15077942  0.63613984  1.51695219] 0.7572558998540831
600 [ 0.49450906 -0.15327296  0.63384165  1.51574858] 0.7559470580458482
700 [ 0.4941322  -0.15576332  0.63154733  1.51454897] 0.7546423349642396
800 [ 0.49375269 -0.1582505   0.62925688  1.51335335] 0.7533417296201084
900 [ 0.49337053 -0.16073448  0.62697031  1.51216173] 0.7520452410095869
1000 [ 0.49298574 -0.16321527  0.62468762  1.51097412] 0.7507528681143767


array([ 0.49298574, -0.16321527,  0.62468762,  1.51097412])

##1*. Измените функцию calc_logloss так, чтобы нули по возможности не попадали в np.log. 

варианта - два:

1. применить отклонение на минимальное число (1e-15)

2. использовать логические выражения

In [17]:
# log less error to avoid np.log(0)
## option 1
def calc_logloss(y, y_pred):
    err = - np.mean(y * np.log(y_pred + 1e-15) + (1.0 - y) * np.log(1.0 - y_pred + 1e-15))
    err = np.sum(err)
    return err

# log less error to avoid np.log(0)
## option 2
def calc_logloss(y, y_pred):
    y_logic = y == 1
    err = sum(-np.log(y_pred[y_logic])) + sum(-np.log(1 - y_pred[~y_logic]))
    # err = - np.mean(y * np.log(y_pred[t]) + (1.0 - y) * np.log(1.0 - y_pred[~t]))
    # err = np.sum(err)
    return err

# evaluate log regression model
def eval_model_log(x, y, iterations, alpha=1e-4, verb=True):
    np.random.seed(42)
    w = np.random.randn(x.shape[0])
    for i in range(1, iterations+1):
        z = np.dot(w, x)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/x.shape[1] * np.dot((y_pred - y), x.T))
        if verb == True:
            if i % (iterations / 10) == 0:
                print(i, w, err)
    return w

eval_model_log(my_stnd(x, [0]), y, iterations=1000, alpha=1e-4)

100 [ 0.49635335 -0.14077362  0.64537112  1.52180639] 7.625324736043117
200 [ 0.49598986 -0.14327981  0.64305753  1.52058688] 7.612071473029914
300 [ 0.49562367 -0.14578284  0.64074779  1.51937134] 7.598859435316546
400 [ 0.49525481 -0.14828271  0.63844189  1.51815977] 7.5856886136308
500 [ 0.49488327 -0.15077942  0.63613984  1.51695219] 7.572558998540831
600 [ 0.49450906 -0.15327296  0.63384165  1.51574858] 7.559470580458482
700 [ 0.4941322  -0.15576332  0.63154733  1.51454897] 7.546423349642396
800 [ 0.49375269 -0.1582505   0.62925688  1.51335335] 7.533417296201085
900 [ 0.49337053 -0.16073448  0.62697031  1.51216173] 7.520452410095871
1000 [ 0.49298574 -0.16321527  0.62468762  1.51097412] 7.507528681143767


array([ 0.49298574, -0.16321527,  0.62468762,  1.51097412])

#2. Подберите аргументы функции eval_model для логистической регрессии таким образом, чтобы log loss был минимальным.

In [18]:
# evaluate log regression model
iterations = [100, 1000, 10000,  100000]
alphas = [1e-5, 1e-4, 1e-3, 1e-2]

def eval_model_logGrid(x, y, iterations, alphas):
    hist = []
    for n_iteration in iterations:
        for alpha in alphas:
            # print(n_iteration)
            np.random.seed(42)
            w = np.random.randn(x.shape[0])
            for i in range(1, n_iteration+1):
                z = np.dot(w, x)
                y_pred = sigmoid(z)
                err = calc_logloss(y, y_pred)
                w -= alpha * (1/x.shape[1] * np.dot((y_pred - y), x.T))
                if i % (n_iteration / 10) == 0:
                    hist.append([n_iteration, i, alpha, w, err])
    res = hist[np.argmax([hist[i][4] for i in range(len(hist))])]
    print(
        'best_result:'
        f'\nnumber_of_iterations / iteration No: {res[0], res[1]}', 
        f'\nalpha applied: {res[2]}',
        f'\nweights obtained: {res[3]}'
        f'\nerror: {res[4]}',     
    )

    return res[3]

eval_model_logGrid(my_stnd(x, [0]), y, iterations, alphas)

best_result:
number_of_iterations / iteration No: (100, 10) 
alpha applied: 1e-05 
weights obtained: [ 0.49667819 -0.13851537  0.64745663  1.52290733]
error: 7.638366254510217


array([ 0.49667819, -0.13851537,  0.64745663,  1.52290733])

#3. Создайте функцию calc_pred_proba, возвращающую предсказанную вероятность класса 1 (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred_proba).

In [19]:
# returns prediction probabilities for the log regression model
def model_log_proba(x, w):
    z = np.dot(w, x)
    y_pred_proba = sigmoid(z)
    return y_pred_proba

model_log_proba(
    my_stnd(x, [0]),
    eval_model_log(my_stnd(x, [0]), y, 1000, alpha=1e-4, verb=False)
)

array([0.20102364, 0.245594  , 0.69391285, 0.22251326, 0.8405047 ,
       0.28188495, 0.97192569, 0.98010348, 0.19087675, 0.75778041])

## 4. Создайте функцию calc_pred, возвращающую предсказанный класс (на вход подаются W, который уже посчитан функцией eval_model и X, на выходе - массив y_pred).

In [20]:
# returns prediction for the log regression model
def model_log_pred(x, w):
    z = np.dot(w, x)
    y_pred_proba = sigmoid(z)
    y_pred = np.where(y_pred_proba >= 0.5, 1, 0)
    return np.array(y_pred)

model_log_pred(
    my_stnd(x, [0]),
    eval_model_log(my_stnd(x, [0]), y, 1000, alpha=1e-4, verb=False)
)

array([0, 0, 1, 0, 1, 0, 1, 1, 0, 1])

#5. Посчитайте Accuracy, матрицу ошибок, точность и полноту, а также F1 score.

In [21]:
# metrics for the binary classification
def my_metrics(y, y_pred):
    tp, fp, tn, fn = 0, 0, 0, 0
    for i in range(len(y_pred)):
        if y_pred[i] == y[i] == 1:
            tp += 1
        if y_pred[i] == y[i] == 0:
            tn += 1
        if y_pred[i] == 1 and y[i] == 0:
            fp += 1
        if y_pred[i] == 0 and y[i] == 1:
            fn += 1
    prec = tp / (tp + fp)
    rec = tp / (tp + fn)
    accur = (tp + tn) / (tp + tn + fp + fn)
    f_1 = (2 * prec * rec) / (prec + rec)

    print(f'confusion_matrix: \n{np.array([[tn, fp], [fn, tp]])}',
            f'\n\naccuracy: {accur}',
            f'\n\nprecision: {prec}',
            f'\n\nrecall: {rec}',
            f'\n\nf1_score: {f_1}'  
    )

my_predictions = model_log_pred(
    my_stnd(x, [0]),
    eval_model_log(my_stnd(x, [0]), y, 1000, alpha=1e-4, verb=False)
)

my_metrics(y, my_predictions)      

confusion_matrix: 
[[4 1]
 [1 4]] 

accuracy: 0.8 

precision: 0.8 

recall: 0.8 

f1_score: 0.8000000000000002


#6. Могла ли модель переобучиться? Почему?

Высокая вероятность, что модель может переобучиться, т.к. очень мало данных для такого типа задач. Можно было бы попробовать трейн тест плит, но данных и так почти нет.

#7*. Создайте функции eval_model_l1 и eval_model_l2 с применением L1 и L2 регуляризаций соответственно.

In [28]:
# evaluate log regression model with l1 regularization
def eval_model_logL1(x, y, iterations, alpha=1e-4, verb=True, lambda_=1e-7):
    np.random.seed(42)
    w = np.random.randn(x.shape[0])
    for i in range(1, iterations+1):
        z = np.dot(w, x)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/x.shape[1] * np.dot((y_pred - y), x.T) + lambda_ * np.sign(w))
        if verb == True:
            if i % (iterations / 10) == 0:
                print(i, w, err)
    return w

eval_model_logL1(my_stnd(x, [0]), y, iterations=10000)

1000 [ 0.49298573 -0.16321526  0.62468761  1.51097411] 7.507528667525403
2000 [ 0.48899468 -0.18784543  0.60207599  1.49931954] 7.380552670132875
3000 [ 0.48474948 -0.21214733  0.57986044  1.48807154] 7.25768020651282
4000 [ 0.48025951 -0.23611314  0.55804771  1.47723531] 7.138899028528378
5000 [ 0.47553505 -0.25973475  0.53664459  1.46681588] 7.024195737372683
6000 [ 0.47058717 -0.28300375  0.51565787  1.4568181 ] 6.913555697159579
7000 [ 0.46542777 -0.30591144  0.49509434  1.4472466 ] 6.80696278750619
8000 [ 0.46006948 -0.32844886  0.47496075  1.43810583] 6.7043989899544805
9000 [ 0.45452558 -0.35060686  0.45526377  1.42939996] 6.605843811327838
10000 [ 0.44880998 -0.37237615  0.43600992  1.42113292] 6.511273556614789


array([ 0.44880998, -0.37237615,  0.43600992,  1.42113292])

In [27]:
# evaluate log regression model with l2 regularization
def eval_model_logL2(x, y, iterations, alpha=1e-4, verb=True, lambda_=1e-7):
    np.random.seed(42)
    w = np.random.randn(x.shape[0])
    for i in range(1, iterations+1):
        z = np.dot(w, x)
        y_pred = sigmoid(z)
        err = calc_logloss(y, y_pred)
        w -= alpha * (1/x.shape[1] * np.dot((y_pred - y), x.T) + lambda_ * w)
        if verb == True:
            if i % (iterations / 10) == 0:
                print(i, w, err)
    return w

eval_model_logL2(my_stnd(x, [0]), y, iterations=10000)

1000 [ 0.49298573 -0.16321526  0.62468761  1.5109741 ] 7.507528650837847
2000 [ 0.48899469 -0.18784545  0.602076    1.49931953] 7.380552639390054
3000 [ 0.48474949 -0.21214735  0.57986045  1.48807152] 7.25768016424499
4000 [ 0.48025953 -0.23611317  0.55804772  1.47723529] 7.138898977141788
5000 [ 0.47553507 -0.25973479  0.53664461  1.46681586] 7.024195679146119
6000 [ 0.4705872  -0.2830038   0.5156579   1.45681807] 6.913555634241091
7000 [ 0.4654278  -0.30591149  0.49509437  1.44724657] 6.806962721910173
8000 [ 0.46006951 -0.32844892  0.47496079  1.43810579] 6.704398923558818
9000 [ 0.45452562 -0.35060693  0.45526381  1.42939993] 6.605843745871393
10000 [ 0.44881002 -0.37237622  0.43600997  1.42113288] 6.511273493695039


array([ 0.44881002, -0.37237622,  0.43600997,  1.42113288])